name: CI Check - Build Docker image

on:
  push:
    branches: [main]
  pull_request:

env:
  AWS_REGION: "ap-south-1"
  ECR_REPOSITORY: "pb-recruitment-dev-backend-core-repo"
  ECS_SERVICE: "pb-recruitment-dev-backend-core-svc"
  ECS_CLUSTER: "pb-recruitment-dev-ecs-cluster"

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10
    env:
      TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: go test ./...

      - name: Verify Swagger Docs
        run: |
          make swagger
          git diff --exit-code docs/

      - name: Build Docker image
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Building Docker image
          docker build -t pb-recruitment-dev-backend-core:$IMAGE_TAG .
